name: Tests

on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    #----------------------------------------------
    #  checkout repo and set-up python and uv
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Python and uv
      uses: ./.github/actions/setup
    #----------------------------------------------
    #            install dependencies
    #----------------------------------------------
    - name: Install dependencies
      uses: ./.github/actions/install
    #----------------------------------------------
    #      run tests and code quality checks
    #----------------------------------------------
    - name: Run tests
      uses: ./.github/actions/test

